name: Cleanup Old Test Reports

on:
  schedule:
    - cron: '0 1 * * *'  # Every day at 01:00 UTC
  workflow_dispatch:  # Also runnable manually

jobs:
  delete-old-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Delete files older than 2 days
        run: |
          find test-reports/ -type f -name "*.html" -mtime +2 -delete

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Cleanup old reports" || echo "No changes to commit"
          git push
